// Code generated by protoc-gen-go.
// source: pb/dlog.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

Version 1.0

It is generated from these files:
	pb/dlog.proto

It has these top-level messages:
	LogSet
	LogEntry
	L7GFrame
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LogSet struct {
	Time     int64       `protobuf:"varint,1,opt,name=time" json:"time,omitempty"`
	Logentry []*LogEntry `protobuf:"bytes,2,rep,name=logentry" json:"logentry,omitempty"`
}

func (m *LogSet) Reset()                    { *m = LogSet{} }
func (m *LogSet) String() string            { return proto.CompactTextString(m) }
func (*LogSet) ProtoMessage()               {}
func (*LogSet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LogSet) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *LogSet) GetLogentry() []*LogEntry {
	if m != nil {
		return m.Logentry
	}
	return nil
}

type LogEntry struct {
	L7G *L7GFrame `protobuf:"bytes,1,opt,name=l7g" json:"l7g,omitempty"`
}

func (m *LogEntry) Reset()                    { *m = LogEntry{} }
func (m *LogEntry) String() string            { return proto.CompactTextString(m) }
func (*LogEntry) ProtoMessage()               {}
func (*LogEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LogEntry) GetL7G() *L7GFrame {
	if m != nil {
		return m.L7G
	}
	return nil
}

type L7GFrame struct {
	Srcmac  string `protobuf:"bytes,1,opt,name=srcmac" json:"srcmac,omitempty"`
	Srcip   string `protobuf:"bytes,2,opt,name=srcip" json:"srcip,omitempty"`
	Popid   string `protobuf:"bytes,3,opt,name=popid" json:"popid,omitempty"`
	Poptime int64  `protobuf:"varint,4,opt,name=poptime" json:"poptime,omitempty"`
	Brtime  int64  `protobuf:"varint,5,opt,name=brtime" json:"brtime,omitempty"`
	Rssi    int32  `protobuf:"varint,6,opt,name=rssi" json:"rssi,omitempty"`
	Lqi     int32  `protobuf:"varint,7,opt,name=lqi" json:"lqi,omitempty"`
	Payload []byte `protobuf:"bytes,8,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *L7GFrame) Reset()                    { *m = L7GFrame{} }
func (m *L7GFrame) String() string            { return proto.CompactTextString(m) }
func (*L7GFrame) ProtoMessage()               {}
func (*L7GFrame) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *L7GFrame) GetSrcmac() string {
	if m != nil {
		return m.Srcmac
	}
	return ""
}

func (m *L7GFrame) GetSrcip() string {
	if m != nil {
		return m.Srcip
	}
	return ""
}

func (m *L7GFrame) GetPopid() string {
	if m != nil {
		return m.Popid
	}
	return ""
}

func (m *L7GFrame) GetPoptime() int64 {
	if m != nil {
		return m.Poptime
	}
	return 0
}

func (m *L7GFrame) GetBrtime() int64 {
	if m != nil {
		return m.Brtime
	}
	return 0
}

func (m *L7GFrame) GetRssi() int32 {
	if m != nil {
		return m.Rssi
	}
	return 0
}

func (m *L7GFrame) GetLqi() int32 {
	if m != nil {
		return m.Lqi
	}
	return 0
}

func (m *L7GFrame) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func init() {
	proto.RegisterType((*LogSet)(nil), "pb.LogSet")
	proto.RegisterType((*LogEntry)(nil), "pb.LogEntry")
	proto.RegisterType((*L7GFrame)(nil), "pb.L7GFrame")
}

func init() { proto.RegisterFile("pb/dlog.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x90, 0xc1, 0x4e, 0xc4, 0x20,
	0x10, 0x86, 0x43, 0xd9, 0x76, 0xeb, 0xb8, 0x26, 0x86, 0x18, 0xc3, 0xc9, 0x34, 0x3d, 0x11, 0x0f,
	0x35, 0xd1, 0xc3, 0x3e, 0x81, 0xeb, 0x65, 0x4f, 0xf8, 0x04, 0xa5, 0x6d, 0x08, 0x09, 0x95, 0x91,
	0xf6, 0xb2, 0x6f, 0xe7, 0xa3, 0x19, 0x66, 0xcb, 0xde, 0xe6, 0xfb, 0x7e, 0xf8, 0x33, 0x00, 0x0f,
	0x68, 0xde, 0x46, 0x1f, 0x6c, 0x87, 0x31, 0xac, 0x41, 0x14, 0x68, 0xda, 0x13, 0x54, 0xe7, 0x60,
	0xbf, 0xa7, 0x55, 0x08, 0xd8, 0xad, 0x6e, 0x9e, 0x24, 0x6b, 0x98, 0xe2, 0x9a, 0x66, 0xa1, 0xa0,
	0xf6, 0xc1, 0x4e, 0x3f, 0x6b, 0xbc, 0xc8, 0xa2, 0xe1, 0xea, 0xfe, 0xfd, 0xd0, 0xa1, 0xe9, 0xce,
	0xc1, 0x7e, 0x26, 0xa7, 0x6f, 0x69, 0xfb, 0x0a, 0x75, 0xb6, 0xe2, 0x05, 0xb8, 0x3f, 0x5a, 0x2a,
	0xca, 0x17, 0x8e, 0x5f, 0xa7, 0xd8, 0xcf, 0x93, 0x4e, 0x41, 0xfb, 0xc7, 0xa0, 0xce, 0x46, 0x3c,
	0x43, 0xb5, 0xc4, 0x61, 0xee, 0x07, 0x3a, 0x7f, 0xa7, 0x37, 0x12, 0x4f, 0x50, 0x2e, 0x71, 0x70,
	0x28, 0x0b, 0xd2, 0x57, 0x48, 0x16, 0x03, 0xba, 0x51, 0xf2, 0xab, 0x25, 0x10, 0x12, 0xf6, 0x18,
	0x90, 0xb6, 0xdf, 0xd1, 0xf6, 0x19, 0x53, 0xbb, 0x89, 0x14, 0x94, 0x14, 0x6c, 0x94, 0x1e, 0x1b,
	0x97, 0xc5, 0xc9, 0xaa, 0x61, 0xaa, 0xd4, 0x34, 0x8b, 0x47, 0xe0, 0xfe, 0xd7, 0xc9, 0x3d, 0xa9,
	0x34, 0x52, 0x6f, 0x7f, 0xf1, 0xa1, 0x1f, 0x65, 0xdd, 0x30, 0x75, 0xd0, 0x19, 0x4d, 0x45, 0x3f,
	0xf8, 0xf1, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x9c, 0x73, 0x73, 0x1a, 0x52, 0x01, 0x00, 0x00,
}
