// Code generated by protoc-gen-go. DO NOT EDIT.
// source: xbos.proto

package pb

/*
This defines the protocol buffers used by XBOS with WaveMQ. The schema for
a wavemq xbos proto message is:
  xbosproto/RootMessageType

Version 1.0
*/

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Root union type
// We reserve 50 fields per imported file
type XBOS struct {
	// Hamilton Fields
	HamiltonData         *HamiltonData        `protobuf:"bytes,50,opt,name=HamiltonData,proto3" json:"HamiltonData,omitempty"`
	HamiltonBRLinkStats  *HamiltonBRLinkStats `protobuf:"bytes,51,opt,name=HamiltonBRLinkStats,proto3" json:"HamiltonBRLinkStats,omitempty"`
	HamiltonBRMessage    *HamiltonBRMessage   `protobuf:"bytes,52,opt,name=HamiltonBRMessage,proto3" json:"HamiltonBRMessage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *XBOS) Reset()         { *m = XBOS{} }
func (m *XBOS) String() string { return proto.CompactTextString(m) }
func (*XBOS) ProtoMessage()    {}
func (*XBOS) Descriptor() ([]byte, []int) {
	return fileDescriptor_xbos_669a49ee0abffa03, []int{0}
}
func (m *XBOS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XBOS.Unmarshal(m, b)
}
func (m *XBOS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XBOS.Marshal(b, m, deterministic)
}
func (dst *XBOS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XBOS.Merge(dst, src)
}
func (m *XBOS) XXX_Size() int {
	return xxx_messageInfo_XBOS.Size(m)
}
func (m *XBOS) XXX_DiscardUnknown() {
	xxx_messageInfo_XBOS.DiscardUnknown(m)
}

var xxx_messageInfo_XBOS proto.InternalMessageInfo

func (m *XBOS) GetHamiltonData() *HamiltonData {
	if m != nil {
		return m.HamiltonData
	}
	return nil
}

func (m *XBOS) GetHamiltonBRLinkStats() *HamiltonBRLinkStats {
	if m != nil {
		return m.HamiltonBRLinkStats
	}
	return nil
}

func (m *XBOS) GetHamiltonBRMessage() *HamiltonBRMessage {
	if m != nil {
		return m.HamiltonBRMessage
	}
	return nil
}

func init() {
	proto.RegisterType((*XBOS)(nil), "proto.XBOS")
}

func init() { proto.RegisterFile("xbos.proto", fileDescriptor_xbos_669a49ee0abffa03) }

var fileDescriptor_xbos_669a49ee0abffa03 = []byte{
	// 147 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xaa, 0x48, 0xca, 0x2f,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x52, 0x7c, 0x19, 0x89, 0xb9, 0x99,
	0x39, 0x25, 0xf9, 0x79, 0x10, 0x61, 0xa5, 0xab, 0x8c, 0x5c, 0x2c, 0x11, 0x4e, 0xfe, 0xc1, 0x42,
	0xe6, 0x5c, 0x3c, 0x1e, 0x50, 0x29, 0x97, 0xc4, 0x92, 0x44, 0x09, 0x23, 0x05, 0x46, 0x0d, 0x6e,
	0x23, 0x61, 0x88, 0x32, 0x3d, 0x64, 0xa9, 0x20, 0x14, 0x85, 0x42, 0x3e, 0x5c, 0xc2, 0x30, 0xbe,
	0x53, 0x90, 0x4f, 0x66, 0x5e, 0x76, 0x70, 0x49, 0x62, 0x49, 0xb1, 0x84, 0x31, 0x58, 0xbf, 0x14,
	0x9a, 0x7e, 0x24, 0x15, 0x41, 0xd8, 0xb4, 0x09, 0xb9, 0x71, 0x09, 0x22, 0x84, 0x7d, 0x53, 0x8b,
	0x8b, 0x13, 0xd3, 0x53, 0x25, 0x4c, 0xc0, 0x66, 0x49, 0x60, 0x98, 0x05, 0x95, 0x0f, 0xc2, 0xd4,
	0x92, 0xc4, 0x06, 0x56, 0x6b, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x79, 0x70, 0x1b, 0x02, 0x03,
	0x01, 0x00, 0x00,
}
